<?php
/**
 * File containing the configuration of various plugin elements.
 *
 * @package osdxp-dashboard
 */

namespace OSDXP_Dashboard;

/**
 * Method to return the DXP menu pages structure array.
 *
 * @return array
 */
function get_dxp_menu_pages()
{
	static $dxp_pages;

	// Build the array only once.
	if (! $dxp_pages) {
		$dxp_pages = [
			[
				'type'       => OSDXP_DASHBOARD_MENU_TYPE_MENU,
				// Arguments as required by add_menu_page().
				'page_title' => esc_html__('Modules', 'osdxp-dashboard'),
				'menu_title' => esc_html__('Modules', 'osdxp-dashboard'),
				'capability' => 'manage_options',
				'menu_slug'  => 'dxp-modules-installed',
				'function'   => __NAMESPACE__ . '\\dxp_render_installed_modules',
				'position_network' => '18',
				'network'    => 'both', //omit to hide from network, true for only, both for both
			],
			[
				//declare first submenu page from dxp-modules to rewrite title for autogenerated subpage
				'type'        => OSDXP_DASHBOARD_MENU_TYPE_SUBMENU,
				// Arguments as required by add_submenu_page().
				'parent_slug' => 'dxp-modules-installed',
				'page_title'  => esc_html__('Installed Modules', 'osdxp-dashboard'),
				'menu_title'  => esc_html__('Installed Modules', 'osdxp-dashboard'),
				'capability'  => 'manage_options',
				'menu_slug'   => 'dxp-modules-installed',
				'function'    => __NAMESPACE__ . '\\dxp_render_installed_modules',
				'network'   => 'both'
			],
			[
				'type'       => OSDXP_DASHBOARD_MENU_TYPE_SUBMENU,
				'parent_slug' => 'dxp-modules-installed',
				'page_title' => esc_html__('Available Modules', 'osdxp-dashboard'),
				'menu_title' => esc_html__('Available Modules', 'osdxp-dashboard'),
				'capability' => 'manage_options',
				'menu_slug'  => 'dxp-modules',
				'function'   => __NAMESPACE__ . '\\dxp_render_available_modules',
				'network'    => 'true',
			],
			[
				'type'        => OSDXP_DASHBOARD_MENU_TYPE_ENDPOINT,
				'parent_slug'   => 'dxp-modules-installed',
				'page_title'  => esc_html__('Upgrade Modules', 'osdxp-dashboard'),
				'menu_title'  => esc_html__('Upgrade Modules', 'osdxp-dashboard'),
				'capability'  => 'manage_options',
				'menu_slug'   => 'dxp-modules-update',
				'function'    => __NAMESPACE__ . '\\dxp_render_update_modules',
				'network'   => 'both'
			],
			[
				'type'        => OSDXP_DASHBOARD_MENU_TYPE_ENDPOINT,
				'parent_slug'   => 'dxp-modules-installed',
				'page_title'  => esc_html__('Modules Information', 'osdxp-dashboard'),
				'menu_title'  => esc_html__('Modules Information', 'osdxp-dashboard'),
				'capability'  => 'manage_options',
				'menu_slug'   => 'dxp-modules-information',
				'function'    => __NAMESPACE__ . '\\dxp_render_update_modules_information',
				'network'   => 'both'

			],
			[
				'type'             => OSDXP_DASHBOARD_MENU_TYPE_MENU,
				'page_title'       => esc_html__('Module Settings', 'osdxp-dashboard'),
				'menu_title'       => esc_html__('Module Settings', 'osdxp-dashboard'),
				'capability'       => 'manage_options',
				'menu_slug'        => 'dxp-module-settings',
				'function'         => __NAMESPACE__ . '\\dxp_render_module_settings',
				'position_network' => '19',
				'network'          => 'both'
			],
		];

		$custom_pages = [];
		$custom_pages = apply_filters('osdxp_add_module_settings_page', $custom_pages);

		foreach ($custom_pages as $custom_page) {
			if (isset($custom_page['page_title'])
				&& isset($custom_page['menu_title'])
				&& isset($custom_page['menu_slug'])
				&& isset($custom_page['function'])
			) {
				$custom_page['type'] = isset($custom_page['type'])
					? $custom_page['type']
					: OSDXP_DASHBOARD_MENU_TYPE_SUBMENU;
				$custom_page['parent_slug'] = isset($custom_page['parent_slug'])
					? $custom_page['parent_slug']
					: 'dxp-module-settings';
				$custom_page['capability'] = isset($custom_page['capability'])
					? $custom_page['capability']
					: 'manage_options';

				$dxp_pages[] = $custom_page;
			}
		}
	}

	return $dxp_pages;
}

/**
 * Get update data for modules
 *
 * @return int number of module updates
 */
function osdxp_get_update_data()
{
	$count = 0;

	if (current_user_can('update_plugins')) {
		$update_modules = get_site_transient('update_plugins');
		$all_modules = apply_filters('osdxp_get_modules', get_plugins());
		if (isset($update_modules->response)) {
			$response = $update_modules->response;
			$count = count(array_intersect_key($response, $all_modules));
		}
	}

	return $count;
}
